// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnjdhmdeczjylcwkvsta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuamRobWRlY3pqeWxjd2t2c3RhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MzU5OTcsImV4cCI6MjA2MjExMTk5N30.6wdmeZxpx2HavrsSbxZY8ZAJcw7pTcjgOHb67zVcW9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);